### ISSUE TITLE
I have some errors, can you healp me?

### ISSUE THREAD

**Issue by Yaguar666** [Icehunter/ffxivapp-sample-plugin#2]
Error	1	The tag 'VisibilityConverter' does not exist in XML namespace 'clr-namespace:FFXIVAPP.Common.Converters;assembly=FFXIVAPP.Common'. Line 15 Position 10.	H:\Users\Yaguar666\Desktop\ffxivapp-sample-plugin-master\Sample.Plugin\ShellView.xaml	15	10	Sample.Plugin

What's wrong i do?

**Comment by Icehunter** [comment]
Are you using the latest resources repo from here?

https://github.com/Icehunter/ffxivapp-resources

Clone that one down and change the references for each DLL to those.

**Comment by Yaguar666** [comment]
Maked it.
Project build in debug mode on 100%, but when I open MainView.xaml that make error.
![2015-05-27_221514](https://cloud.githubusercontent.com/assets/12599900/7845194/113b4768-04be-11e5-9c60-bb21c2a684e8.png)

**Comment by Icehunter** [comment]
Can you paste the xaml here for that?

**Comment by Yaguar666** [comment]
<UserControl x:Class="Sample.Plugin.Views.MainView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:Controls="clr-namespace:FFXIVAPP.Common.Controls;assembly=FFXIVAPP.Common"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:ViewModels="clr-namespace:Sample.Plugin.ViewModels"
             xmlns:Sample="clr-namespace:Sample.Plugin"
             xmlns:Properties="clr-namespace:Sample.Plugin.Properties"
             d:DesignHeight="300"
             d:DesignWidth="300"
             mc:Ignorable="d">

    <UserControl.Resources>
        <ResourceDictionary>
            <x:Static x:Key="MainViewModel"
                      Member="ViewModels:MainViewModel.Instance" />
            <x:Static x:Key="PluginViewModel"
                      Member="Sample:PluginViewModel.Instance" />
            <x:Static x:Key="Settings"
                      Member="Properties:Settings.Default" />
        </ResourceDictionary>
    </UserControl.Resources>

    <Grid x:Name="LayoutRoot"
          DataContext="{StaticResource MainViewModel}">
        <StackPanel>
            <TabControl>
                <TabItem Header="{Binding Locale[sample_ChatLogTabHeader],
                                          Source={StaticResource PluginViewModel}}">
                    <Controls:xFlowDocument x:Name="ChatLogFD" />
                </TabItem>
            </TabControl>
        </StackPanel>
    </Grid>
</UserControl>

**Comment by Yaguar666** [comment]
<UserControl x:Class="Sample.Plugin.Views.MainView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:Controls="clr-namespace:FFXIVAPP.Common.Controls;assembly=FFXIVAPP.Common"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:ViewModels="clr-namespace:Sample.Plugin.ViewModels"
             xmlns:Sample="clr-namespace:Sample.Plugin"
             xmlns:Properties="clr-namespace:Sample.Plugin.Properties"
             d:DesignHeight="300"
             d:DesignWidth="300"
             mc:Ignorable="d">

    <UserControl.Resources>
        <ResourceDictionary>
            <x:Static x:Key="MainViewModel"
                      Member="ViewModels:MainViewModel.Instance" />
            <x:Static x:Key="PluginViewModel"
                      Member="Sample:PluginViewModel.Instance" />
            <x:Static x:Key="Settings"
                      Member="Properties:Settings.Default" />
        </ResourceDictionary>
    </UserControl.Resources>

    <Grid x:Name="LayoutRoot"
          DataContext="{StaticResource MainViewModel}">
        <StackPanel>
            <TabControl>
                <TabItem Header="{Binding Locale[sample_ChatLogTabHeader],
                                          Source={StaticResource PluginViewModel}}">
                    <Controls:xFlowDocument x:Name="ChatLogFD" />
                </TabItem>
            </TabControl>
        </StackPanel>
    </Grid>
</UserControl>

**Comment by Yaguar666** [comment]
<UserControl x:Class="Sample.Plugin.Views.MainView"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:Controls="clr-namespace:FFXIVAPP.Common.Controls;assembly=FFXIVAPP.Common"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:ViewModels="clr-namespace:Sample.Plugin.ViewModels"
             xmlns:Sample="clr-namespace:Sample.Plugin"
             xmlns:Properties="clr-namespace:Sample.Plugin.Properties"
             d:DesignHeight="300"
             d:DesignWidth="300"
             mc:Ignorable="d">

**Comment by Yaguar666** [comment]
<UserControl.Resources>
        <ResourceDictionary>
            <x:Static x:Key="MainViewModel"
                      Member="ViewModels:MainViewModel.Instance" />
            <x:Static x:Key="PluginViewModel"
                      Member="Sample:PluginViewModel.Instance" />
            <x:Static x:Key="Settings"
                      Member="Properties:Settings.Default" />
        </ResourceDictionary>
    </UserControl.Resources>

    <Grid x:Name="LayoutRoot"
          DataContext="{StaticResource MainViewModel}">
        <StackPanel>
            <TabControl>
                <TabItem Header="{Binding Locale[sample_ChatLogTabHeader],
                                          Source={StaticResource PluginViewModel}}">
                    <Controls:xFlowDocument x:Name="ChatLogFD" />
                </TabItem>
            </TabControl>
        </StackPanel>
    </Grid>

**Comment by Yaguar666** [comment]
& all in 
<UserControl x:Class="Sample.Plugin.Views.MainView"
</UserControl>

**Comment by Yaguar666** [comment]
& all in 
UserControl x:Class="Sample.Plugin.Views.MainView"
/UserControl

**Comment by Icehunter** [comment]
I'm not getting that myself; opened in VS2013 but not getting the error on build. Have you made any modifications? If not I would suggest cloning it down again.

I have my folder structure as My Documents\GitHub and I've cloned all the projects I have into that folder so they can self reference a bit better.

**Comment by Yaguar666** [comment]
Ok, it have no errors, have many warnings... but it work)
When i take WidgetsPlugin, rename it in all files & etc. Build it.
Now i load all on Git, use SourseURL to install plugin.
It was installed, but after reload FFXIVAPP plugin be in "NotInstalled".
Where i'm wrong?

I want to modify the plug in order that it reads the log (or the memory, have not decided yet), compared to the base of the original translation and gave a Russian translation. In general, I want to do quests translator, subtitles and etc. from English into Russian for all Russian community)
True, I know little C ++, Mathab, AuthoIT, PHP, CSS, HTML, and first encounter with GIT, C # / XAML)
If you can help or teach me anything it will accelerate the process of creating a plugin)

Thank you for understanding ^_^

**Comment by Yaguar666** [comment]
Code https://github.com/Yaguar666/ffxivapp-plugin-qtr
